services:
  postgres:
    image: postgres:16
    container_name: spotify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass
      POSTGRES_DB: spotify_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: